spring:
  application:
    name: SupportDesk API
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/supportdesk
    username: supportdesk
    password: supportdesk
